[package]
name = "dp-live"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.dp]
tier = 1

[dependencies]
log = "0.4.34"
deadlock-reader = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "e4d31fb8669a514839f0df3c9f4a003e99496a49" }
deadlock-walker = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "e4d31fb8669a514839f0df3c9f4a003e99496a49" }
