[package]
name = "dp-live"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.dp]
tier = 1

[dependencies]
log = "0.4.34"
deadlock-reader = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "8712248d9efcc70ed15ca628d1bde0607f3251b0" }
deadlock-walker = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "8712248d9efcc70ed15ca628d1bde0607f3251b0" }
