[package]
name = "dp-live"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.dp]
tier = 1

[dependencies]
log = "0.4.34"
deadlock-reader = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "756d61a1d1b970e0855b786ffe9914098a41df27" }
deadlock-walker = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "756d61a1d1b970e0855b786ffe9914098a41df27" }
