[package]
name = "dp-gamedata"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.dp]
tier = 2

[dependencies]
dp-steam = { path = "../../ring1/dp-steam" }
deadlock-data = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "0e5ae08347c65f0032b7701022878ca37adf22c3", default-features = false, features = ["bundled", "client", "vpk", "serde", "art"] }
log = "0.4.34"
serde = { version = "1", features = ["derive"] }
ts-rs = "12"
