[package]
name = "dp-voice-bans"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.dp]
tier = 2

[dependencies]
dp-atomic = { path = "../../ring0/dp-atomic" }
dp-sync = { path = "../../ring0/dp-sync" }
dp-game = { path = "../../ring1/dp-game" }
dp-steam = { path = "../../ring1/dp-steam" }
log = "0.4.34"
serde = { version = "1", features = ["derive"] }
ts-rs = "12"
