[package]
name = "dp-firewall"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
dp-atomic = { path = "../../ring0/dp-atomic" }
dp-sync = { path = "../../ring0/dp-sync" }
log = "0.4.34"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58", features = ["Win32_NetworkManagement_WindowsFirewall", "Win32_System_Com", "Win32_Foundation"] }
