[package]
name = "dp-postgame"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.dp]
tier = 1

[dependencies]
log = "0.4.34"
serde = { version = "1", features = ["derive"] }
ts-rs = "12"
valveprotos = { git = "https://github.com/deadlock-api/deadlock-api", rev = "19a34aa9cedabd3374cb4af5c2d714520784ce1f", features = ["gc-common", "gc-client"] }

[dev-dependencies]
serde_json = "1"

[target.'cfg(windows)'.dependencies]
deadlock-reader = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "a54dd811d65f58c2ccdd123a1e1654bf975ba86d" }
deadlock-events = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "a54dd811d65f58c2ccdd123a1e1654bf975ba86d" }
