[package]
name = "dp-postgame"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[package.metadata.dp]
tier = 1

[dependencies]
log = "0.4.34"
serde = { version = "1", features = ["derive"] }
ts-rs = "12"
serde_json = "1"
valveprotos = { git = "https://github.com/deadlock-api/deadlock-api", rev = "19a34aa9cedabd3374cb4af5c2d714520784ce1f", features = ["gc-common", "gc-client", "serde"] }
deadlock-reader = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "8712248d9efcc70ed15ca628d1bde0607f3251b0" }
deadlock-events = { git = "https://github.com/deadlock-plus/deadlock-rs", rev = "8712248d9efcc70ed15ca628d1bde0607f3251b0" }
